# Generated by Django 4.0 on 2021-12-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee')], max_length=30, verbose_name='Роль'),
        ),
    ]
